service: MINUTAS

provider:
  name: aws
  runtime: python3.11

functions:
  create_minuta_hipoteca:
    handler: controllers.minuta_hipoteca.create_hipoteca
    events:
      - http:
          path: /minuta/create/serverless
          method: post